### ISSUE TITLE
Cannot make static method

### ISSUE THREAD

**Issue by easydowork** [mix-php/mix-skeleton#1]
php7.3 bin/mix.php web:start
[error] 2020-04-22 06:51:12.870 <64042> Cannot make static method Mix\Route\Router::show404() non static in class App\Web\Route\Router
[code] 64 [type] Mix\Console\Exception\ErrorException
[file] in /Users/mac/Documents/wwwroot/swoole/mix-skeleton/app/Web/Route/Router.php on line 12
 #0 [internal function]: Mix\Console\Error->appShutdown()
 #1 {main}
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.17
Built => Apr 22 2020 14:37:42
coroutine => enabled
kqueue => enabled
rwlock => enabled
sockets => enabled
pcre => enabled
zlib => 1.2.11
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

**Comment by onanying** [comment]
@easydowork  这个是我手贱改了这个位置搞得不兼容了，你修改这个文件 /Users/mac/Documents/wwwroot/swoole/mix-skeleton/app/Web/Route/Router.php 的 show404 show500 方法，看一下他继承的父类有没有 static 搞成一样的即可，这个位置我还反复改过几次。
